name: dockerhub-publish
on:
  release:
    types:
      - created
jobs:
 main:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: xlanor/rtorrent-flood:latest
          build-args: |
            USER_ID=${{ secrets.USERID }}
            GROUP_ID=${{ secrets.GROUPID }}
            FSECRET=${{ secrets.FSECRET }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}